#!/usr/bin/env python3
import os
import boto3

import aws_cdk as cdk
from infra.infra_stack import InfraStack
import cdk_nag as nag

account_id = boto3.client('sts').get_caller_identity().get('Account')
region = os.getenv('AWS_REGION', 'us-west-2')

app = cdk.App()
infra = InfraStack(app, "SageMakerVCPOnlyMLflow",
    env=cdk.Environment(account=account_id, region=region)
)

cdk.Aspects.of(app).add(nag.AwsSolutionsChecks(verbose=True))

nag.NagSuppressions.add_stack_suppressions(
     infra,
    [
        {
            "id": "AwsSolutions-IAM4",
            "reason": "Suppress AwsSolutions-IAM5 for S3 bucket since they are generated by custom resources",
            "appliesTo": [
                'Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole',
            ]
        },
        {
            "id": 'AwsSolutions-L1',
            "reason": 'Lambda function is generated by CDK'
        }
    ]
)

nag.NagSuppressions.add_resource_suppressions_by_path(
    stack=infra,
    path=f"/{infra.stack_name}/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/ServiceRole/DefaultPolicy/Resource",
    suppressions=[
        {
            "id": 'AwsSolutions-L1',
            "reason": "Policies are set by Custom Resource.",
        },
        {
            "id": 'AwsSolutions-IAM5',
            "reason": "Policies are set by Custom Resource.",
        }
    ]
)

app.synth()